# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "server" do | m1 |
    m1.vm.box = "StefanScherer/windows_2019"
    m1.vm.network "private_network", ip: "172.19.0.10"
    m1.vm.hostname = "server-lba"
    m1.vm.provider "virtualbox" do |vb|
      vb.name = "server-lba"
      vb.memory = 4096
      vb.cpus = 4
    end
  end

  config.vm.define "client" do | m2 |
    m2.vm.box = "scotch/box"
    m2.vm.network "private_network", ip: "172.19.0.11"
    m2.vm.hostname = "client-lba"
    m2.vm.provider "virtualbox" do |vb|
      vb.name = "client-lba"
      vb.memory = 2048
      vb.cpus = 2
    end
  end

end