# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "web-lba"
  config.vm.provider "virtualbox" do | vb|
    vb.name = "Web Server"
    vb.memory = 3072
    vb.cpus = 2
  end
  config.vm.network  "private_network", ip: "172.16.200.10"
  config.vm.network  "public_network", ip: "10.9.9.10"
end
